language: python
sudo: false

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy"
  - "pypy3"

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - libffi-dev
      - libssl-dev
      - python-dev
      - python-pip
      - swig

install:
  - pip install --disable-pip-version-check --upgrade pip
  - pip install -r dev-requirements.txt
  - pip install -e .

script:
  - coverage run setup.py test

after_success:
  - coveralls
